version: '2'
services:
  redis:
    image: redis:4-alpine
    volumes:
      - ./data:/data
  app:
    build: ./
    ports:
      - 5001:5000
    links:
      - redis
    environment:
      - PORT=5000
      - REDIS_URL=redis